
services:
  redis-service:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    ports:
      - "6379:6379"
  dilmil-api:
    build: .
    ports:
      - "5000:5000"
    command: /bin/bash docker-entrypoint.sh
    volumes:
      - .:/gpanel
    depends_on:
      - db
      - redis-service
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dilmil
    ports:
      - 5432:5432

volumes:
  postgres_data: