services:
  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - my-network

  dilmil-api:
    build: .
    ports:
      - "5000:5000"
    command: /bin/bash docker-entrypoint.sh
    volumes:
      - .:/gpanel
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - my-network

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dilmil
    ports:
      - 5432:5432
    networks:
      - my-network

volumes:
  postgres_data:
  data:

networks:
  my-network: