"""indexing

Revision ID: 487d7f033ba3
Revises: d33d63105ad6
Create Date: 2024-05-13 23:22:17.191551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487d7f033ba3'
down_revision = 'd33d63105ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_profiles_dob'), ['dob'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_profiles_height'), ['height'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_profiles_height'))
        batch_op.drop_index(batch_op.f('ix_users_profiles_dob'))

    # ### end Alembic commands ###
